### ISSUE TITLE
guild members

### ISSUE THREAD

**Issue by kyssuuwuas** [nevafold/Voleur-Stealer#1]
![image](https://user-images.githubusercontent.com/128225295/229904379-5ea34c97-55b5-4334-8b5f-131ab7abb615.png)
i have it enabled but still gives error

**Comment by Fosnos** [comment]
npm i discord.js@v13

**Comment by kyssuuwuas** [comment]
> npm i discord.js@v13

thanks it worked, do you maybe know how to get a api?

**Comment by kyssuuwuas** [comment]
@nevafold do you got the site src?

**Comment by trickogg** [comment]
> npm i discord.js@v13

lol
