### ISSUE TITLE
doenst build 

### ISSUE THREAD

**Issue by kyssuuwuas** [nevafold/Voleur-Stealer#2]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/128225295/230441183-c0ca3b3c-86fb-41b9-9455-b9d8d6435a88.png">
<img width="381" alt="image" src="https://user-images.githubusercontent.com/128225295/230441270-5c02351c-a9e0-4b7a-8166-6383c3cac94f.png">
someone help pls

**Comment by trickogg** [comment]
> <img width="523" alt="image" src="https://user-images.githubusercontent.com/128225295/230441183-c0ca3b3c-86fb-41b9-9455-b9d8d6435a88.png">
> 
> <img width="381" alt="image" src="https://user-images.githubusercontent.com/128225295/230441270-5c02351c-a9e0-4b7a-8166-6383c3cac94f.png">
> 
> someone help pls
> 
> 

lmao bros trying to make his own stealer 🤭

**Comment by kyssuuwuas** [comment]
> 

nigga, i use it for mine self, it has mine rl name in it 😁

**Comment by kyssuuwuas** [comment]
but it still doenst build xD
