### ISSUE TITLE
it doenst build (who helps me gets 4 eu pp / ltc)

### ISSUE THREAD

**Issue by kyssuuwuas** [nevafold/Voleur-Stealer#3]
![image](https://user-images.githubusercontent.com/128225295/230493521-eb884373-d904-4deb-8e11-99ccd4058e40.png)

**Comment by kyssuuwuas** [comment]
if you help me 4 eu ltc or pp

**Comment by lolk11** [comment]
send discord user

**Comment by lolk11** [comment]
> if you help me 4 eu ltc or pp

send discord user

**Comment by kyssuuwuas** [comment]
> send discord user

Haunter#5555

**Comment by lolk11** [comment]
> > send discord user
> 
> Haunter#5555

Check fucking friend requests

**Comment by kyssuuwuas** [comment]
discord = termed dm me here

**Comment by kyssuuwuas** [comment]
fixed
